### ISSUE TITLE
Azure HPC Cache name is limited to 31 characters instead of 80

### ISSUE THREAD

**Issue by jsmartt** [Azure/azure-sdk-for-ruby#2759] opened 2020-02-19 23:05 UTC
Many places in [this file](https://github.com/Azure/azure-sdk-for-ruby/blob/master/management/azure_mgmt_storagecache/lib/2019-11-01/generated/azure_mgmt_storagecache/caches.rb), there is a regex, validating the name matches the pattern `^[-0-9a-zA-Z_]{1,31}$`. It will prevent any action (including get or create) with a name longer than 31 characters by raising the following error:

```ruby
ArgumentError: 'cache_name' should satisfy the constraint - 'Pattern': '^[-0-9a-zA-Z_]{1,31}$'
```

However, the Azure console shows the following validation:

![Screen Shot 2020-02-19 at 4 01 21 PM](https://user-images.githubusercontent.com/5340733/74884776-2d7ea980-5331-11ea-84d1-106b08d2e381.png)

The API validation allows 80 characters, so I'm guessing this SDK needs updated.

**Comment by MyronFanQiu** [comment] 2020-02-20 02:06
@jsmartt Hello. Our SDK is auto-generated. The root cause is that service team set this limitation in their swagger spec. We have to fix it in the swagger spec first. I add service attention to invite correct team. 
https://github.com/Azure/azure-rest-api-specs/blob/62b1b41dd4637c3667943aa5b845f08e81671437/specification/storagecache/resource-manager/Microsoft.StorageCache/stable/2019-11-01/storagecache.json#L269

But it's better to open a PR in this repo https://github.com/Azure/azure-rest-api-specs/

**Comment by jsmartt** [comment] 2020-03-05 17:13
Thanks @MyronFanQiu. I did open a PR on that repo, but it looks like it needs some help from some MSFT folks to fix build/validation issues and enable SDK automation.

**Comment by MyronFanQiu** [comment] 2020-03-06 02:46
Could you give me the PR link?

**Comment by jsmartt** [comment] 2020-03-06 15:23
It's linked just above my comment too, but it's https://github.com/Azure/azure-rest-api-specs/pull/8606

**Comment by romahamu** [comment] 2020-03-12 19:07
Hi @jsmartt thanks for pointing it out.

@MyronFanQiu There is a new version coming, which has this fix.  https://github.com/Azure/azure-rest-api-specs/pull/8403/files

**Comment by MyronFanQiu** [comment] 2020-03-13 01:35
@romahamu good to know. Once it's merged, you can request a sdk release through https://portal.azure-devex-tools.com/

**Comment by lilyjma** [comment] 2021-01-08 00:45
Hi, this issue appears to be resolved, so I'm closing it now. Thanks!

**Closed by lilyjma** 2021-01-08 00:45 UTC
Labels: Service Attention, Storage, customer-reported
