### ISSUE TITLE
AzureStack - Provide option to customize storage and keyvault data plane endpoint suffix

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-sdk-for-ruby#1116] opened 2017-11-08 01:14 UTC
For azurestack environments the storage and keyvault endpoint suffix are all different .  we need a way to customize storage_endpoint_suffix and key_vault_dns_suffix

**Comment by veronicagg** [comment] 2017-11-15 19:21
Seems like a duplicate of https://github.com/Azure/azure-sdk-for-ruby/issues/1118, @sarangan12 is looking into this and will reply in the other issue.

**Closed by veronicagg** 2017-11-15 19:21 UTC
Labels: Sprint-110, v1.0

**Comment by bganapa** [comment] 2017-12-07 21:42
Not really a duplicate, but I think this can be handled as part of the linked issue https://github.com/Azure/azure-sdk-for-ruby/issues/1118
