### ISSUE TITLE
Error Occurs while passing EncryptionConfig Object to Azure Data Lake Store Account

### ISSUE THREAD

**Issue by muhammad-asad-confiz** [Azure/azure-sdk-for-ruby#899] opened 2017-08-17 11:22 UTC
Hi,

I am trying to create a data lake store account using SDK but I am getting following error
**Invalid parameters: Payload.EncryptionConfig.MsiSecretUri**
If I do not pass the encryption config object then the account is created successfully but as I pass the encryption config object along with other parameters error occurs.

The object I am passing is below:

```
#<Azure::ARM::DataLakeStore::Models::DataLakeStoreAccount:0x0055ab093daa18 
@name="fogtestdls", 
@location="East US 2", 
@type="Microsoft.DataLakeStore/accounts", 
@firewall_state="Enabled", 
@firewall_allow_azure_ips="Enabled", 
@firewall_rules=[
#<Azure::ARM::DataLakeStore::Models::FirewallRule:0x0055ab09f92950 
@name="one", 
@start_ip_address="116.58.62.100", 
@end_ip_address="116.58.62.110">
], 
@encryption_state="Enabled", 
@encryption_config=
#<Azure::ARM::DataLakeStore::Models::EncryptionConfig:0x0055ab09f86bf0 
@type="UserManaged", 
@key_vault_meta_info=
#<Azure::ARM::DataLakeStore::Models::KeyVaultMetaInfo:0x0055ab09f7e4f0 @key_vault_resource_id="/subscriptions/My Subscription ID/resourceGroups/TestRG-ZN/providers/Microsoft.KeyVault/vaults/testdlskeyvault", 
@encryption_key_name="testdlskey", 
@encryption_key_version='My Key Version'
>>, 
@new_tier="Consumption", 
@current_tier="Consumption"
>
```

but when I pass this object the data lake account is created successfully.

```
#<Azure::ARM::DataLakeStore::Models::DataLakeStoreAccount:0x0055ab093daa18 
@name="fogtestdls", 
@location="East US 2", 
@type="Microsoft.DataLakeStore/accounts", 
@firewall_state="Enabled", 
@firewall_allow_azure_ips="Enabled", 
@firewall_rules=[
#<Azure::ARM::DataLakeStore::Models::FirewallRule:0x0055ab09f92950 
@name="one", @start_ip_address="116.58.62.100", 
@end_ip_address="116.58.62.110">
], 
@encryption_state="Enabled", 
@new_tier="Consumption", 
@current_tier="Consumption"
>
```

**Comment by abbas-sheikh-confiz** [comment] 2017-08-24 09:52
Hello Azure SDK Team,

Is this issue under consideration?

**Comment by sarangan12** [comment] 2017-09-07 22:36
@abbas-sheikh-confiz 

This is a duplicate of issue https://github.com/Azure/azure-sdk-for-ruby/issues/933. The specific error is a service side issue and not an SDK related issue. 

 have spoken with @ro-joowan and confirmed that this is a service side issue. SDK has no pending action on this. @ro-joowan will coordinate with the you in https://social.msdn.microsoft.com/Forums/azure/en-US/e77524ad-3401-4714-bd66-63ba80b95e32/data-lake-store-azure-sdk-ruby?forum=AzureDataLake

Closing this issue as there is no pending action from SDK team

**Closed by sarangan12** 2017-09-07 22:36 UTC
Labels: Sprint-106
