### ISSUE TITLE
Unable to Add Traffic Manager Endpoint with Traffic Manager Profile

### ISSUE THREAD

**Issue by maham-nazir-confiz** [Azure/azure-sdk-for-ruby#2716] opened 2019-09-24 11:09 UTC
Hi, I'm trying to create a `Traffic Manager Profile` that also has a `Traffic Manager Endpoint` included in it. However, my SDK requests fails with the following error

```
"body": "{\"code\":\"BadRequest\",\"message\":\"Endpoint name '' is invalid. 
Endpoint names cannot be empty or all whitespace, and must be up to 260 alphanumeric characters long. 
The type '<null>' specified for endpoint '<null>' is invalid. Valid endpoint types are: 
'Microsoft.Network\\/trafficManagerProfiles\\/azureEndpoints', 
'Microsoft.Network\\/trafficManagerProfiles\\/externalEndpoints', 
'Microsoft.Network\\/trafficManagerProfiles\\/nestedEndpoints'.\"}"
```

This is my request body
```
<Azure::TrafficManager::Mgmt::V2018_04_01::Models::Profile:0x0055c26806f678 
@traffic_routing_method="Performance", @location="global", @profile_status="Enabled", @dns_config=#<Azure::TrafficManager::Mgmt::V2018_04_01::Models::DnsConfig:0x0055c26806f650 
@relative_name="testapplication", @ttl="30">, @monitor_config=#<Azure::TrafficManager::Mgmt::V2018_04_01::Models::MonitorConfig:0x0055c26806f628 
@path="/monitorpage.aspx", @protocol="http", @port="80">, @endpoints=[#<Azure::TrafficManager::Mgmt::V2018_04_01::Models::Endpoint:0x0055c26806f538 
@min_child_endpoints=nil, @target_resource_id=nil, @endpoint_location="eastus", @priority=5, 
@target="test-app.com", @weight=10, @name="endpoint1", 
@type="Microsoft.Network/trafficManagerProfiles/externalEndpoints">], @tags={:key1=>"value1", :key2=>"value2"}>
```

This is the request body created by the SDK

```
"body": "{\"tags\":{\"key1\":\"value1\",\"key2\":\"value2\"},\"location\":\"global\",\"properties\":
{\"profileStatus\":\"Enabled\",\"trafficRoutingMethod\":\"Performance\",\"dnsConfig\":
{\"relativeName\":\"testapplication\",\"ttl\":\"30\"},\"monitorConfig\":
{\"protocol\":\"http\",\"port\":\"80\",\"path\":\"/monitorpage.aspx\"},\"endpoints\":[{\"properties\":
{\"target\":\"test-app.com\",\"weight\":10,\"priority\":5,\"endpointLocation\":\"eastus\"}}]}}"
```

As seen, the `name` and `type` attribute of the `endpoint` are not added in the body even though I included them in my parameters. I checked the `Endpoint` model and I see that these attribute types have been set to `read_only`. I am not sure what that means exactly. All I can infer is that because they have been set `read_only` so Traffic Manager Profile is not able to set their values.

Can someone please let me know how I can create a Traffic Manager Profile with an Endpoint included as well? Thanks

**SDK Version:** 0.17.2

**Comment by sfiguemsft** [comment] 2019-09-24 23:17
@rohinkoul can you look into this please?

**Comment by rohinkoul** [comment] 2019-09-24 23:54
@sfiguemsft looks like an SDK bug.

**Comment by MyronFanQiu** [comment] 2019-09-25 02:06
@rohinkoul Based on [swagger](https://github.com/Azure/azure-rest-api-specs/blob/e0ee56c9ef0293d4d43a07e3fb7685e0e479cf1d/specification/trafficmanager/resource-manager/Microsoft.Network/stable/2018-04-01/trafficmanager.json#L1460), the name and the id are set to `read_only=true`. There is a [rule](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-13) that read only property must not be sent as part of the request. Ruby SDK strictly follows the rule so that user cannot set this property. Based on my knowledge, the swagger spec should be corrected since it violated the rule.

**Comment by maham-nazir-confiz** [comment] 2019-09-25 03:49
@MyronFanQiu I would like to add some more information.
 
This situation only happens in the case when I am trying to create a TM Profile with an Endpoint included. If I create it without an Endpoint, it works. Also if I create only an Endpoint object, then I am able to do that as well. It only doesn't work in case of creating a TM Profile with an Endpoint included.

Also this `read_only: true` change has been around for a long time. It was first made available in the tag branch `ms_rest_azure-v0.8.2`. I am not convinced that this is a bug, if it were it would have been reported a long time ago. 

If someone can please provide me with a sample example of how I can create a TM Profile with an Endpoint included, that would be most helpful.

**Comment by MyronFanQiu** [comment] 2019-09-27 01:21
@rohinkoul Hello. Any thoughts?

**Comment by maham-nazir-confiz** [comment] 2019-10-01 04:25
@MyronFanQiu  @rohinkoul 
Do you guys have any update on this? Please let me know. Thank you.

**Comment by maham-nazir-confiz** [comment] 2019-10-08 08:45
@MyronFanQiu  
I am working on upgrading a library that uses Azure SDK and I am blocked by this. Please let me know how this issue can be resolved. Thanks.

**Comment by MyronFanQiu** [comment] 2019-10-08 10:28
@maham-nazir-confiz Hello. From Ruby SDK perspective, it is by design that user cannot set read_only field. It's not a bug. In my opinion, the swagger should be changed. I have sent an email to @rohinkoul and we should have a good discussion about this issue.

**Comment by maham-nazir-confiz** [comment] 2019-10-08 11:08
@MyronFanQiu 
I am able to set the `read_only` fields when I am trying to create a TM Endpoint only.

This is only happening when creating/updating a TM Endpoint inside a TM Profile as I have shown in the example above.

Is there another way to create a TM Endpoint with a TM Profile?

**Comment by MyronFanQiu** [comment] 2019-10-08 11:25
@maham-nazir-confiz Hello, Which `read_only` field you can set to create a TM Endpoint?  Let me do some investigations about that. 
One workaround might be that you could try to use azure-mgmt-resource to send an ARM template to create the Endpoint with TM Profile.

**Comment by maham-nazir-confiz** [comment] 2019-10-08 11:39
The `name` and `type` attributes for a TM Endpoint.
Try creating a TM Endpoint and add values for both the `name` and the `type` attributes.
These are marked `read_only`. Reference [Link](https://github.com/Azure/azure-sdk-for-ruby/blob/a6d67518a874f55684a8a46eab68219a0107288a/management/azure_mgmt_traffic_manager/lib/2018-04-01/generated/azure_mgmt_traffic_manager/models/endpoint.rb#L94)

**Comment by MyronFanQiu** [comment] 2019-10-08 12:12
@maham-nazir-confiz  Are you able to set these two fields? There is a comment https://github.com/Azure/azure-sdk-for-ruby/blob/a6d67518a874f55684a8a46eab68219a0107288a/management/azure_mgmt_traffic_manager/lib/2018-04-01/generated/azure_mgmt_traffic_manager/models/endpoint.rb#L74.
Based on my knowledge, you can set these fields.
https://github.com/Azure/azure-sdk-for-ruby/blob/a6d67518a874f55684a8a46eab68219a0107288a/management/azure_mgmt_traffic_manager/lib/2018-04-01/generated/azure_mgmt_traffic_manager/models/endpoint.rb#L17-L69
You can check the request body, I think the endpoint parameter doesn't include the name and the type. However, you can set the name through this function. You need to set the type and the name. https://github.com/Azure/azure-sdk-for-ruby/blob/a6d67518a874f55684a8a46eab68219a0107288a/management/azure_mgmt_traffic_manager/lib/2018-04-01/generated/azure_mgmt_traffic_manager/endpoints.rb#L267
If you find the name and the type in the endpoint in the request body, please let me know. Thanks 😄

**Comment by MyronFanQiu** [comment] 2019-10-08 12:13
@maham-nazir-confiz For the endpoint creation, the server exposes the type and the name as two independent parameters.

**Comment by maham-nazir-confiz** [comment] 2019-10-08 12:46
@MyronFanQiu 
I will try the code again and get back to you.

```
For the endpoint creation, the server exposes the type and the name as two independent parameters.
```

Can you please elaborate on this?

Thanks.

**Comment by maham-nazir-confiz** [comment] 2019-10-09 03:08
@MyronFanQiu 
Yes you're right. I am indeed setting the `name` and `type` via the function parameters not as part of the request body.

However, these attributes were exposed before in SDK version 0.9.0.

So now is there no way to create a TM Endpoint along with a TM Profile? Do I need to create an Endpoint separately now?

**Comment by MyronFanQiu** [comment] 2019-10-14 06:48
@sfiguemsft Hello. Could you give some thoughts about this issue? @maham-nazir-confiz Sorry for delay. We are quite busy recently.

**Comment by maham-nazir-confiz** [comment] 2019-10-14 12:09
@MyronFanQiu 

This is also affecting the update of a TM Profile. If I update it without the TM Endpoints included, it just removes all the endpoints already added to it. If I add a TM Endpoint object (obtained via GET call), and use that in the request body, I am still getting the main issue.

**Comment by sfiguemsft** [comment] 2019-10-14 14:58
the update will always require the other configuration details to be included too ( this is not specific to TM ) , as swagger this needs @rohinkoul input

**Comment by maham-nazir-confiz** [comment] 2019-10-28 11:12
@MyronFanQiu @sfiguemsft 
any update on when you will be releasing the fix? Thanks

**Comment by MyronFanQiu** [comment] 2019-11-06 05:59
@maham-nazir-confiz Sorry for the delay. I tried to open an issue for you in the https://github.com/Azure/azure-rest-api-specs/ repo. And I just found existed one
https://github.com/Azure/azure-rest-api-specs/issues/1940. @rohinkoul Is any plan to solve this one?

**Comment by rohinkoul** [comment] 2019-11-26 22:39
@MyronFanQiu endpoint name has to be specified while creating a new endpoint. It can't be changed once the endpoint has been created and hence I guess it has been marked as read-only. What would be the SDK behavior if we mark it read/write? I am a bit confused about why this would be a problem specifically for Ruby SDK and not others. Before updating swagger I need to make sure that this does not affect the rest of the SDKs

**Comment by MyronFanQiu** [comment] 2019-11-27 05:09
@rohinkoul Hi. In the Azure/azure-rest-api-specs#1940, python SDK has met same problem before. `readonly: true` means that this property should not appear in the PUT REST CALL. In Ruby, we will not expose this parameter to user. In Python, this property will be filtered out of body content even if the user provide this parameter.

**Comment by maham-nazir-confiz** [comment] 2019-11-27 05:22
@rohinkoul it's not about changing the name of an already created endpoint. It's about being able to create an endpoint along with a TM Profile which is something that was allowed back in SDK 0.9.0

Now even if we have to create an endpoint separately, when trying to update a TM Profile, you cannot pass it your endpoint and hence the TM Profile ends up losing any endpoints it had on update

**Comment by maham-nazir-confiz** [comment] 2020-01-20 05:34
@MyronFanQiu  any update on when this will get fixed?

Thank you

**Comment by MyronFanQiu** [comment] 2020-01-30 04:40
@maham-nazir-confiz  sorry for the delay. The issue must be solved in swagger spec and I can release a new version of Ruby SDK. @rohinkoul Since python sdk has met same problem two years ago. Could you please investigate the issue and update swagger spec?

**Comment by yunbas** [comment] 2020-02-14 22:15
@maham-nazir-confiz  we added this bug to our backlog. Our current plan is to address this by the end of June 2020. We are not able to provide a more certain ETA at the moment.

**Comment by nabeel-nazir-confiz** [comment] 2020-03-02 13:50
@yunbas I am facing the same issue can you please release the fix for this mentioned bug?

**Comment by kurtzeborn** [comment] 2023-01-11 03:35
Thank you for your interest in Azure SDKs.  As detailed in this [retirement announcement](https://github.com/Azure/azure-sdk-for-ruby#important-announcement), this repo is no longer supported as of December 31st 2021.  Please find the up-to-date list of languages and services supported with Azure SDKs here: https://aka.ms/azsdk

**Closed by kurtzeborn** 2023-01-11 03:35 UTC
Labels: bug, Network - Traffic Manager, Service Attention, customer-reported, Mgmt
