### ISSUE TITLE
time out issue

### ISSUE THREAD

**Issue by dandagopi** [Azure/azure-sdk-for-ruby#1243] opened 2018-01-19 00:01 UTC
ruby vm_create.rb 
long_running_operation_retry_timeout = 30
/usr/share/ruby/net/http.rb:878:in `initialize': Connection timed out - connect(2) (Faraday::TimeoutError)
    from /usr/share/ruby/net/http.rb:878:in `open'
    from /usr/share/ruby/net/http.rb:878:in `block in connect'
    from /usr/share/ruby/timeout.rb:52:in `timeout'
    from /usr/share/ruby/net/http.rb:877:in `connect'
    from /usr/share/ruby/net/http.rb:862:in `do_start'
    from /usr/share/ruby/net/http.rb:851:in `start'
    from /usr/share/ruby/net/http.rb:1373:in `request'
    from /usr/local/share/gems/gems/rest-client-1.6.7/lib/restclient/net_http_ext.rb:51:in `request'
    from /usr/share/ruby/net/http.rb:1131:in `get'
    from /usr/local/share/gems/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:78:in `perform_request'
    from /usr/local/share/gems/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:38:in `block in call'
    from /usr/local/share/gems/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
    from /usr/local/share/gems/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:33:in `call'
    from /usr/local/share/gems/gems/faraday-cookie_jar-0.0.6/lib/faraday/cookie_jar.rb:22:in `call'
    from /usr/local/share/gems/gems/ms_rest-0.6.4/lib/ms_rest/retry_policy_middleware.rb:29:in `call'
    from /usr/local/share/gems/gems/faraday-0.13.1/lib/faraday/rack_builder.rb:141:in `build_response'
    from /usr/local/share/gems/gems/faraday-0.13.1/lib/faraday/connection.rb:387:in `run_request'
    from /usr/local/share/gems/gems/ms_rest-0.6.4/lib/ms_rest/http_operation_request.rb:80:in `block in run_promise'
    from /usr/local/share/gems/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:24:in `call'
    from /usr/local/share/gems/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
    from /usr/local/share/gems/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
    from /usr/local/share/gems/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
    from /usr/local/share/gems/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
    from /usr/local/share/gems/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
    from /usr/local/share/gems/gems/concurrent-ruby-1.0.5/lib/concurrent/promise.rb:531:in `block in realize'
    from /usr/local/share/gems/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `call'
    from /usr/local/share/gems/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
    from /usr/local/share/gems/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
    from /usr/local/share/gems/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
    from /usr/local/share/gems/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
    from /usr/local/share/gems/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
    from /usr/local/share/gems/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'

**Comment by rameshjanjyam** [comment] 2018-01-19 00:17
Here is the script that was run 

```
require 'json'
require 'chef'
require 'azure_mgmt_resources'
require 'azure_mgmt_compute'
require 'azure_mgmt_storage'

def get_credentials(tenant_id, client_id, client_secret)
  begin
    # Create authentication objects
    token_provider =
        MsRestAzure::ApplicationTokenProvider.new(tenant_id,
                                                  client_id,
                                                  client_secret)
    MsRest::TokenCredentials.new(token_provider)
  rescue MsRestAzure::AzureOperationError => e
    puts("Error acquiring a token from Azure: #{e.body}")
  rescue => ex
    puts("Error acquiring a token from Azure: #{ex.message}")
  end
end

#provide enough info to talk to azure apis here
tenant_id = ENV['t_id']
subscription_id = ENV['s_id']
client_id = ENV['cid']
client_secret = ENV['cst']
resource_group_name = ENV['rg_name']
vm_name = ENV['vm_name']

credentials = get_credentials(tenant_id, client_id, client_secret)
client = Azure::ARM::Compute::ComputeManagementClient.new(credentials)
client.subscription_id = subscription_id

begin
  promise = client.virtual_machines.get_async(resource_group_name, vm_name)
  response = promise.value!
  puts "reponse is = #{response.inspect}"
  result = response.body
rescue MsRest::DeserializationError => e
  puts ("exception msg = #{e.exception_message}")
  puts ("msg = #{e.message}")
  puts ("stacktrace = #{e.exception_stacktrace}")
  puts ("response body when error = #{e.response_body}")
end

puts result.inspect
```

**Comment by sarangan12** [comment] 2018-01-19 22:50
@dandagopi @rameshjanjyam Thanks for reporting the issue and providing the code. I looked into the code and tried it myself and it seems to work fine. I am not able to reproduce the timeout issue. I believe that the error might be the result of the way the network has been setup. I might be able to provide more information only if I get access to the environment.

In the meantime, I suggest setting the ```ENV['AZURE_HTTP_LOGGING'] = true``` in the code and execute the code. This will provide detailed debug logs which might point out the root cause of the error.

**Comment by sarangan12** [comment] 2018-01-19 23:31
Mail from Sushant Rane:

Hello Team,

We were able to find the cause of the issue. The issue happens while calling Azure ARM API over public peering. OneOps was experiencing intermittent timeout issues, while making a connection to management.azure.com API endpoint. 

The timeouts are observed when the endpoint resolves to a datacenter IP not in their allowed BGP Community for public peering. We have resolved the issue, by allowing the application to communicate over proxy, but with higher latency. 

In this scenario, the OneOps inductor is in EastUS2, but the calls to management.azure.com are going to Canada East Datacenter, which is not advertised on edge routers.

I am trying to find if there is a more deterministic approach to route the api to certain datacenters only. 

Thanks and appreciate your help.

Regards,

Sushant Rane

**Comment by sarangan12** [comment] 2018-01-19 23:31
As there is no pending action items on this issue, I am closing this issue.

**Closed by sarangan12** 2018-01-19 23:31 UTC

**Comment by rameshjanjyam** [comment] 2018-01-20 00:07
Thank you @sarangan12.

**Comment by SimonKaluza** [comment] 2018-12-04 04:37
I've experienced a burst of these timeouts during VM create operations using the Azure ARM API... They happen intermittently even on VM nodes -- is there anyway to work around them?  I'm experimenting with increasing my Faraday timeouts to absurdly high numbers, but many of these requests seem to be hanging indefinitely after doing that.
