### ISSUE TITLE
Error while creating SQL Server using azure_mgmt_sql gem

### ISSUE THREAD

**Issue by shaffan-chaudhry-confiz** [Azure/azure-sdk-for-ruby#701] opened 2017-02-28 14:27 UTC
I am creating an sql server using **azure_mgmt_sql** gem and it is created successfully on the portal. But I am getting **Invalid json** error at this line number: https://github.com/Azure/azure-sdk-for-ruby/blob/master/management/azure_mgmt_sql/lib/generated/azure_mgmt_sql/servers.rb#L644.

I debugged the response and found out that response is in XML format and this line of code is trying to parse it as a json. This is the reason I am getting **invalid json** error.

**Comment by devigned** [comment] 2017-02-28 15:42
Wow, that is unexpected behavior. I'm surprised to hear XML is returned from that method. Could you share response and the error message your are receiving?

**Comment by shaffan-chaudhry-confiz** [comment] 2017-03-01 06:18
Screen shots of the response.

![1](https://cloud.githubusercontent.com/assets/16117183/23448048/97f0848c-fe70-11e6-9814-80b72034d84d.png)
![2](https://cloud.githubusercontent.com/assets/16117183/23448049/981a7576-fe70-11e6-9eb6-d8103061ca8c.png)
![3](https://cloud.githubusercontent.com/assets/16117183/23448050/981cd712-fe70-11e6-945e-0a8081e29365.png)

**Comment by devigned** [comment] 2017-03-01 15:41
@vishrutshah, @sarangan12 and @akromm can you guys give this a look. It looks like the api is returning xml when it's clearly requesting `application/json`.

**Comment by akromm** [comment] 2017-03-01 17:41
I don't see any "accept" header in the request payload.

Can you try adding:
`Accept: application/json`
to the request headers?

**Comment by devigned** [comment] 2017-03-01 17:55
@akromm the header has `application/json; charset=utf-8`, which should be acceptable as application/json.

**Comment by akromm** [comment] 2017-03-01 18:11
that is the `content-type` header which describes the request content.  The `accept` tells the server in which format to respond.

**Comment by devigned** [comment] 2017-03-01 18:47
@akromm good point

**Comment by vishrutshah** [comment] 2017-03-01 18:53
Yup this seems like a bug in our client to not defaulting to `Accept: application/json`.

**Comment by sarangan12** [comment] 2017-03-09 20:10
Changes committed to runtime. Will be available in the next release.

**Closed** 2017-03-09 20:10 UTC
Labels: arm, azure_mgmt_sql, bug, runtime
