### ISSUE TITLE
Azure::Blob::BlobService#get_blob yields incomplete data

### ISSUE THREAD

**Issue by milgner** [Azure/azure-sdk-for-ruby#402] opened 2016-07-05 22:15 UTC
We recently started noticing a fair amount of incomplete blobs (~80-90%) after downloading them from Azure. There are no errors being raised, so I have added some code to check for correctness of the downloaded MD5:

```ruby
loop do
  metadata, blob = @service.get_blob(container, name)
  expected = metadata.properties[:content_md5]
  actual = Base64.encode64(Digest::MD5.digest(blob))
  break if expected == actual
  # log...
end
```

This of course is quite ugly but I don't know what the problem could be. Since downloading them using other means works just fine, I must assume it's a problem with the Ruby library?
For blobs of about 80kb, the size of the downloaded blobs usually range from 40-60kb. So it might even be something straightforward like a buffer not being flushed.

**Comment by devigned** [comment] 2016-07-06 14:07
Yes, that should be done in the library. Thank you for bringing this up.

The storage bits have been moved into their own library [here](https://github.com/Azure/azure-storage-ruby). Please open the issue there. We'll keep this open and update the dependency in this project (if needed).

**Comment by milgner** [comment] 2016-07-06 14:40
So the separate storage gem can be considered stable? The `README` in this projects still describes it as "preview gem", so I wasn't sure about starting to use it.

**Comment by yaxia** [comment] 2016-08-17 09:10
@milgner The code in the azure-storage is mostly the same or improved based on this repo. It is "preview" because there is still a gap between the azure-storage gem and the storage services provided via REST APIs.

I cannot reproduce your issue with the azure-storage gem. Could you move to the azure-storage and try again? Thanks.

**Comment by veronicagg** [comment] 2016-08-29 17:20
Please reopen if you see errors after moving to azure-storage.

**Closed by veronicagg** 2016-08-29 17:20 UTC
Labels: Storage
