### ISSUE TITLE
list_blobs not requesting proper uri

### ISSUE THREAD

**Issue by gatneil** [Azure/azure-sdk-for-ruby#397] opened 2016-06-10 00:48 UTC
Hello! I tried to execute the ruby code here:
```
client = Azure.client(storage_account_name: storage_account_name, storage_access_key: storage_access_key)
list = client.blobs.list_blobs(container)
```

This errors consistently with `/Users/pivotal/.rubies/ruby-2.2.5/lib/ruby/2.2.0/net/http.rb:879:in `initialize': getaddrinfo: nodename nor servname provided, or not known (Faraday::ConnectionFailed)`

Callstack here:

	from /Users/pivotal/.rubies/ruby-2.2.5/lib/ruby/2.2.0/net/http.rb:879:in `open'
	from /Users/pivotal/.rubies/ruby-2.2.5/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
	from /Users/pivotal/.rubies/ruby-2.2.5/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
	from /Users/pivotal/.rubies/ruby-2.2.5/lib/ruby/2.2.0/net/http.rb:878:in `connect'
	from /Users/pivotal/.rubies/ruby-2.2.5/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /Users/pivotal/.rubies/ruby-2.2.5/lib/ruby/2.2.0/net/http.rb:852:in `start'
	from /Users/pivotal/.rubies/ruby-2.2.5/lib/ruby/2.2.0/net/http.rb:1375:in `request'
	from /Users/pivotal/.rubies/ruby-2.2.5/lib/ruby/2.2.0/net/http.rb:1133:in `get'
	from /Users/pivotal/.gem/ruby/2.2.5/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	from /Users/pivotal/.gem/ruby/2.2.5/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Users/pivotal/.gem/ruby/2.2.5/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Users/pivotal/.gem/ruby/2.2.5/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Users/pivotal/.gem/ruby/2.2.5/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:76:in `perform_with_redirection'
	from /Users/pivotal/.gem/ruby/2.2.5/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:64:in `call'
	from /Users/pivotal/.gem/ruby/2.2.5/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/pivotal/.gem/ruby/2.2.5/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Users/pivotal/.gem/ruby/2.2.5/gems/azure-core-0.1.2/lib/azure/core/http/http_request.rb:150:in `call'
	from /Users/pivotal/.gem/ruby/2.2.5/gems/azure-core-0.1.2/lib/azure/core/http/signer_filter.rb:28:in `call'
	from /Users/pivotal/.gem/ruby/2.2.5/gems/azure-core-0.1.2/lib/azure/core/http/signer_filter.rb:28:in `call'
	from /Users/pivotal/.gem/ruby/2.2.5/gems/azure-core-0.1.2/lib/azure/core/http/http_request.rb:104:in `block in with_filter'
	from /Users/pivotal/.gem/ruby/2.2.5/gems/azure-core-0.1.2/lib/azure/core/service.rb:36:in `call'
	from /Users/pivotal/.gem/ruby/2.2.5/gems/azure-core-0.1.2/lib/azure/core/filtered_service.rb:34:in `call'
	from /Users/pivotal/.gem/ruby/2.2.5/gems/azure-core-0.1.2/lib/azure/core/signed_service.rb:41:in `call'
	from /Users/pivotal/.gem/ruby/2.2.5/gems/azure-0.7.5/lib/azure/blob/blob_service.rb:1385:in `call'
	from /Users/pivotal/.gem/ruby/2.2.5/gems/azure-0.7.5/lib/azure/blob/blob_service.rb:376:in `list_blobs'
	from ./check:27:in `<main>'

I added a print statement to the Azure.Core.Service.call method so it now looks like:

      def call(method, uri, body=nil, headers={})
        request = Core::Http::HttpRequest.new(method, uri, body: body, headers: headers, client: @client)
        yield request if block_given?
        **p request**
        request.call
      end

re-running the ruby code above, I see the following. It seems the Azure Client object  has the proper storage account name (nsgconcoursestandard), but the http request is missing this part of the blob url. Is this an issue, or have I misunderstood the client object configuration in some way?

#<Azure::Core::Http::HttpRequest:0x007ff7a11c5160 @method=:get, @uri=#<URI::HTTPS **https://.blob.core.windows.net/con1**?restype=container&comp=list>, @client=#<Azure::Client:0x007ff7a135b150 @storage_access_key="manualy redacted by me :)", @**storage_account_name="nsgconcoursestandard**", @sb_access_key=nil, @sb_sas_key=nil, @sb_sas_key_name=nil, @ca_file=nil, @sb_namespace=nil, @certificate_key=nil, @private_key=nil, @management_certificate=nil, @subscription_id=nil, @sql_database_management_endpoint="https://management.core.windows.net:8443/", @sb_issuer="owner", @storage_table_host="https://.table.core.windows.net", @storage_blob_host="https://.blob.core.windows.net", @storage_queue_host="https://.queue.core.windows.net", @management_endpoint="https://management.core.windows.net/">, @headers={"User-Agent"=>"Azure-Core/0.1.2", "x-ms-date"=>"Fri, 10 Jun 2016 00:34:49 GMT", "x-ms-version"=>"2014-02-14", "DataServiceVersion"=>"1.0;NetFx", "MaxDataServiceVersion"=>"2.0;NetFx", "Content-Type"=>"application/atom+xml; charset=utf-8", "Content-Length"=>"0"}, @body=nil, @has_retry_filter=false>

**Comment by yaxia** [comment] 2016-08-17 09:13
@gatneil I cannot reproduce this issue with the azure-storage gem which is based on this repo and improved the storage functions. Would you please move to the azure-storage gem and try again? Thanks.

**Comment by veronicagg** [comment] 2016-08-29 17:21
Please reopen if you see issues after moving to azure-storage.

**Closed by veronicagg** 2016-08-29 17:21 UTC
Labels: Storage
